stages:
 - build
 - test
 - maven_job

cache:
 paths:
   - .m2/repository/

#variables:
 # MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

maven_job:
  stage: maven_job
  script:
    -mvn clean install -DskipTests=true
   
build:
 stage: build
 image: maven:3.5-jdk-8-alpine
 script:
  - mvn test
 artifacts:
  paths:
   - target/*.jar
   - target/*.html
 #  - .m2/repository




