stages:
 - build
 - test
 - maven_job

cache:
 paths:
   - .m2/repository/

#variables:
 # MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

maven_job:
  stage: maven_job
  script:
    -mvn clean test -Psmoke
   





